---
title: "About Connor Treyball"
---


##**My life!**

My name is Connor Treyball and I'm a student at Appalachian State University. I've been studying psychology for the past few years and I have intentions of getting my Master's Degree in I-O psychology. I'm very interested in how and why people do things. I was originally born in Yorktown Heights, New York in 1996. In the year 2008, my family relocated to Greensboro, North Carolina. One of the things that I am most passionate about is psychology. I have multiple family members who are intrigued by or have majored in psychology. My particular areas of interest within psychology are in personality, industrial-organizational, abnormal, and social psychology. Outside of school, I love to exercise and be physically active in general. I'd say my true passion is lifting weights. I go outside or to the gym at least once a day to be active. Something that's unique about myself is the amount of structure and order that goes into my routine. Being conscientious is a blessing and a curse but it's something that plays a big part in my life. I have specific times that I do certain things including: going to bed, waking up, studying, etc. For anyone that reads this page, the thing that I'd like to get across about me is that I care. Everything that I do, I put my heart into and have very high expectations. At the end of the day, I enjoy living life and laughing more than anything.



[My LinkedIn Profile](https://www.linkedin.com/in/connor-treyball-ab4044148)

